import Footer from './compenents/Footer'
import Navbar from './compenents/Navbar'
import './globals.css'
import { Fasthand } from 'next/font/google'

const Fast = Fasthand({
   subsets: ['latin'],
   weight:['400']
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Fast.className}>
      <Navbar/>
      <main className='min-h-[450px] text-center text-2xl'>
        {children}
      </main>
      <Footer/>
      </body>
    </html>
  )
}
